apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kubernetes.io/change-cause: "Chage Description"
    name: deployment-test
    labels:
        app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 100
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: front
spec:
  selector:
    app: front #Es el label del container 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80  # El puerto en el que corre dentro del contenedor