apiVersion: apps/v1
kind: Deployment
metadata:
    name: front-ks8-deployment
    labels:
        app: front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front
        image: front-img
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: front-ks8-service
  labels:
    app: front
spec:
  type: NodePort
  selector:
    app: front #Es el label del container 
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000  # El puerto en el que corre dentro del contenedor